// Dwg_TwoButtons.cpp  file ==============
// generated by pfodWeb Designer Arduino Export V1.0.0
/*   
 * (c)2025 Forward Computing and Control Pty. Ltd.
 * NSW Australia, www.forward.com.au
 * This code is not warranted to be fit for any purpose. You may only use it at your own risk.
 * This generated code may be freely used for both private and commercial use
 * provided this copyright is maintained.
 */

#include "Dwg_TwoButtons.h"
Dwg_TwoButtons dwg_TwoButtons;
pfodDrawing& mainDwg = dwg_TwoButtons;

#include "Dwg_LedOn.h"
Dwg_LedOn dwg_LedOn;
#include "Dwg_LedOff.h"
Dwg_LedOff dwg_LedOff;
extern bool ledOn;

static unsigned long dwgRefresh = 5000;

// return true if handled else false
// either handle cmd here or in main sketch
bool Dwg_TwoButtons::processDwgCmds() {
// byte dwgCmd = parserPtr->parseDwgCmd(); // pfodParse calls this automagically before calling this method
  if (!(*(parserPtr->getDwgCmd()))) {  // ==> getDwgCmd returned pointer to empty string
    return false; // not dwg cmd, not handled
  }

  // Serial.print("dwgCmd did not match:");Serial.println(cmd_c1);
  return false; // not handled
}

bool Dwg_TwoButtons::sendDwg() {
  if (!parserPtr->cmdEquals(*this)) {
    return false; // not this dwg's loadCmd
  }  // else
  if (parserPtr->isRefresh()) { // refresh just send update
    sendUpdate();
  } else {
    sendFullDrawing();
  }
  return true;
}

// all the indexed items are included here, edit as needed for updates
void Dwg_TwoButtons::sendIndexedItems() {
  if (ledOn) {
    dwgsPtr->label().idx(idx_1).color(dwgsPtr->RED).text("Led is On").bold().offset(20,11.5).center().decimals(2).send();
  } else { // off  
    dwgsPtr->label().idx(idx_1).color(dwgsPtr->BLACK).text("Led is Off").bold().offset(20,11.5).center().decimals(2).send();
  }  
}
        
void Dwg_TwoButtons::sendFullDrawing() {
    // Start the drawing
    dwgsPtr->start(40, 15, dwgsPtr->SILVER);
    parserPtr->sendRefreshAndVersion(dwgRefresh); // sets version and refresh time for dwg pfodWeb processes this
    sendIndexedItems(); // send indexed items first so they are available for touchZone accesses        
    dwgsPtr->pushZero(-4, -2, 0.5);
    dwgsPtr->insertDwg().loadCmd(dwg_LedOn).offset(0,0).send();
    dwgsPtr->pushZero(33, 0, 1);
    dwgsPtr->insertDwg().loadCmd(dwg_LedOff).offset(0,0).send();
    dwgsPtr->popZero();
    dwgsPtr->popZero();
    dwgsPtr->end();
}
        
// only indexed items can be sent as an update
// all the indexed items are included here, edit as needed
void Dwg_TwoButtons::sendUpdate() {
    dwgsPtr->startUpdate();
    sendIndexedItems(); // send indexed items first so they are available for touchZone accesses        
    dwgsPtr->end();
}
// ============== end of Dwg_TwoButtons.cpp  file 
