// Dwg_HelloWorldCounter.h  file  =================
// generated by pfodWeb Designer Arduino Export V1.0.1
#ifndef DWG_HelloWorldCounter_H
#define DWG_HelloWorldCounter_H
// Arduino code for drawing: HelloWorldCounter
// Generated from pfod drawing HelloWorldCounter.json
/*   
 * (c)2025 Forward Computing and Control Pty. Ltd.
 * NSW Australia, www.forward.com.au
 * This code is not warranted to be fit for any purpose. You may only use it at your own risk.
 * This generated code may be freely used for both private and commercial use
 * provided this copyright is maintained.
 */
#include <pfodDwgs.h>
#include <pfodDrawing.h>
 
class Dwg_HelloWorldCounter : public pfodDrawing {
  public:
    // C++ auto generates Dwg_HelloWorldCounter() constructor
    bool sendDwg(); // returns true if dwg sent else false i.e. not this dwg's loadCmd
    bool processDwgCmds(); // return true if handled else false

  protected:
    void sendFullDrawing();
    void sendUpdate();
    void sendIndexedItems();
    pfodAutoIdx idx_1;

};
#endif
// ================= end of Dwg_HelloWorldCounter.h  file
